blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),

]

voguish/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^home/', include('home.urls', namespace='home', app_name='home')),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^services/', TemplateView.as_view(template_name='services.html'), name='services'),
    #url(r'^services/', include('services.urls', namespace='services', app_name='services')),
    url(r'^contact/', include('contact.urls', namespace='contact', app_name='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='posts', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # The Dahl-specific manager.

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, FormView, View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Q

from django.views.generic.base import TemplateResponseMixin, View



class PostListView(ListView):
    model = Post
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post_list.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post = self.get_object()
        context['post'] = post

        return context


def post_list(request, tag_slug=None):

    template_name = 'blog/post_list.html'
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    query = request.GET.get("q")
    if query:
        object_list = object_list.filter(
            Q(title__icontains=query) |
            Q(body__icontains=query)

        ).distinct()

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context = {'page': page,
               'posts': posts,
               'tag': tag,
               }

    return render(request, template_name, context)


def post_detail(request, year, month, day, post):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = { 'post': post,
                'comments': comments,
                'comment_form': comment_form,
               }

    return render(request, template_name, context)


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post_share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}Blog{% endblock %}

{% block navigation %}
    {% include "nav.html" with is_blog=True %}
{% endblock %}

{% block content %}
    <div class="content-top">

			<div class="single">
				<div class="single-top">
                    <h3>{{ post.title }}</h3>
					<img src="{{ post.image.url }}" class="img-responsive" alt="">


					<p class="sin">{{ post.body|markdown }}</p>
						<div class="artical-links">
		  						 	<ul>
		  						 		<li><small> </small><span>{{ post.updated }}</span></li>
		  						 		<li><a href="#"><small class="admin"> </small><span>{{ post.author }}</span></a></li>
                                        {% with comments.count as total_comments %}
		  						 		    <li><a href="#"><small class="no"> </small><span>{{ total_comments }} comment{{ total_comments|pluralize }}</span></a></li>
                                        {% endwith %}
		  						 		<li><a href="{% url 'blog:post_list' %}"><small class="posts"> </small><span>View posts</span></a></li>
		  						 		<li><a href="{% url "blog:post_share" post.id %}"><small class="link"> </small><span>Share this post</span></a></li>
		  						 	</ul>
		  						 </div>
						<div class="respon">
							<h2>Responses so far</h2>

                            {% for comment in comments %}
							<div class="strator">
								<h5>#{{ forloop.counter }} by {{ comment.name }}</h5>
								<p>{{ comment.created }}</p>
									<div class="strator-left">
										<img src="{% static 'images/co.png' %}" class="img-responsive" alt="">
									</div>
									<div class="strator-right">
										<p class="sin">{{ comment.body|markdown }}</p>
									</div>
								<div class="clearfix"></div>
								<div class="rep">
{#									<a href="#" class="reply">REPLY</a>#}
								</div>
							</div>
                            {% empty %}
                                <p>There are no comments yet.</p>
                            {% endfor %}


							<div class="comment">
                                {% if new_comment %}
                                    <h2> Your comment has been added.</h2>
                                {% else %}
								<h2>Leave a comment</h2>
								<form action="." method="post">{% csrf_token %}
								 <input type="text" name="name" class="textbox" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
								 <input type="text" name="email" class="textbox" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
{#								  <input type="text" class="textbox" value="Website" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Website';}">#}
								 <textarea name="body" value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message</textarea>
								 <div class="smt1">
									<input type="submit" value="add a comment">
								 </div>

							   </form>
                                {% endif %}
							</div>
						</div>
				</div>
				<div class="blog-content-right">
						{% include "search.html" %}
						<!--start-twitter-weight-->
						{% include "twitter.html" %}
						<!--//End-twitter-weight-->
						<!-- start-tag-weight-->
						{% include "tags.html" %}
						<!---- //End-tag-weight---->
					</div>
					<div class="clearfix"> </div>
			</div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}

{% block title %}Blog{% endblock %}

{% block navigation %}
    {% include "nav.html" with is_blog=True %}
{% endblock %}

{% block content %}
    <div class="blog">

		<div class="blog-content">



					<div class="blog-content-left">
						<div class="blog-articals">


                             {% for post in posts %}
                            <div class="blog-artical">
                                <div class="blog-artical-info">
                                    <div class="blog-artical-info-img">
                                        <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" title="post-name"></a>
                                    </div>
                                    <div class="blog-artical-info-head">
                                        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                                        <h6>Posted on, {{ post.publish }} by <a href="{% url 'about' %}"> {{ post.author }}</a></h6>

                                    </div>
                                    <div class="blog-artical-info-text">
                                        <p>{{ post.body|markdown|truncatewords_html:75 }}<a href="{{ post.get_absolute_url }}">[...]</a></p>
                                    </div>
                                    <div class="artical-links">
                                        <ul>
                                            <li><small> </small><span>june 14, 2013</span></li>
                                            <li><a href="#"><small class="admin"> </small><span>admin</span></a></li>
                                            <li><a href="#"><small class="no"> </small><span>No comments</span></a></li>
                                            <li><a href="#"><small class="posts"> </small><span>View posts</span></a></li>
                                            <li><a href="#"><small class="link"> </small><span>permalink</span></a></li>
                                        </ul>
                                     </div>
                                </div>
                                <div class="clearfix"> </div>
                            </div>

                    {% endfor %}
					</div>
					<!--start-blog-pagenate-->
							{% include "pagination.html" with page=posts %}
				<!--//End-blog-pagenate-->
					</div>
					<div class="blog-content-right">
						{% include "search.html" %}
						<!--start-twitter-weight-->
						{% include "twitter.html" %}
						<!--//End-twitter-weight-->
						<!-- start-tag-weight-->
						{% include "tags.html" %}
						<!---- //End-tag-weight---->
					</div>
					<div class="clearfix"> </div>

				</div>
		</div>

{% endblock %}

blog/templates/blog/post_share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}Share a post{% endblock %}

{% block navigation %}
    {% include "nav.html" with is_blog=True %}
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}

        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form|crispy}}

            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>

    {% endif %}
{% endblock %}