blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),

]

voguish/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^home/', include('home.urls', namespace='home', app_name='home')),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^services/', TemplateView.as_view(template_name='services.html'), name='services'),
    #url(r'^services/', include('services.urls', namespace='services', app_name='services')),
    url(r'^contact/', include('contact.urls', namespace='contact', app_name='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}About{% endblock %}

{% block navigation %}
    {% include "nav.html" with is_about=True %}
{% endblock %}

{% block content %}

    <div class="about">
 			<h2>About</h2>
 			<div class="about-top">
 				 <div class="col-md-6 ab-top">
 				 	<img src="{% static 'images/6.jpg' %}" class="img-responsive" alt="">
 				 </div>
 				 <div class="col-md-6 ab-top">
 				 	<h3>Lorem Ipsum has been the industry's</h3>
 				 	<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. of Lorem Ipsum. PageMaker including versions of Lorem Ipsum.</p>
 					<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions Letraset sheets containing Lorem Ipsum passages, and more recently with including versions of Lorem Ipsum.</p>
 				 </div>
 				 	<div class="clearfix"> </div>
 			</div>
		<div class="team_grid">
       		<h3 class="m_1">Meet Our Team</h3>
       	  <div class="span_3">
       	   <div class="col-md-6 ab-top">
       	  	<ul class="span_2">
       	  		<li class="span_2-left"><img src="{% static 'images/6.jpg' %}" class="img-responsive" alt=""></li>
       	  		<li class="span_2-right">
       	  		  <h3>Gummies lollipop</h3>

       	  		  <p>It is a long established fact that a reader will be distracted by the readable content of a page</p>
       	  		</li>
       	  		<div class="clearfix"> </div>
       	  	</ul>
       	   </div>
       	   <div class="col-md-6 ab-top">
       	  	<ul class="span_2">
       	  		<li class="span_2-left"><img src="{% static 'images/5.jpg' %}" class="img-responsive" alt=""></li>
       	  		<li class="span_2-right">
       	  		  <h3>Gummies lollipop</h3>

       	  		  <p>It is a long established fact that a reader will be distracted by the readable content of a page</p>
       	  		</li>
       	  		<div class="clearfix"> </div>
       	  	</ul>
       	   </div>
       	   		<div class="clearfix"> </div>
       	  </div>
       	  <div class="span_4">
       	   <div class="col-md-6 ab-top">
       	  	<ul class="span_2">
       	  		<li class="span_2-left"><img src="{% static 'images/1.jpg' %}" class="img-responsive" alt=""></li>
       	  		<li class="span_2-right">
       	  		  <h3>Gummies lollipop</h3>

       	  		  <p>It is a long established fact that a reader will be distracted by the readable content of a page</p>

       	  		</li>
       	  		<div class="clearfix"> </div>
       	  	</ul>
       	   </div>
       	   <div class="col-md-6 ab-top">
       	  	<ul class="span_2">
       	  		<li class="span_2-left"><img src="{% static 'images/4.jpg' %}" class="img-responsive" alt=""></li>
       	  		<li class="span_2-right">
       	  		  <h3>Gummies lollipop</h3>

       	  		  <p>It is a long established fact that a reader will be distracted by the readable content of a page</p>

       	  		</li>
       	  		<div class="clearfix"> </div>
       	  	</ul>
       	   </div>
       	   <div class="clearfix"> </div>
       	  </div>
     </div>
     <div class="testimonial">

     		<h3>Our Testimonials</h3>
     		<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum</p>
     	    <ul class="test_icon">
     	    	<li><a href="#"><img src="{% static 'images/1.jpg' %}" class="img-responsive"></a></li>
     	    	<li><a href="#"><img src="{% static 'images/2.jpg' %}" class="img-responsive"></a></li>
     	    	<li><a href="#"><img src="{% static 'images/3.jpg' %}" class="img-responsive"></a></li>
     	    	<li><a href="#"><img src="{% static 'images/4.jpg' %}" class="img-responsive"></a></li>
     	    	<li><a href="#"><img src="{% static 'images/5.jpg' %}" class="img-responsive"></a></li>
     	    	<div class="clearfix"> </div>
     	    </ul>

     </div>
    </div>
{% endblock %}

templates/banner.html
{% load static %}
<div class="fle-xsel">
			<ul id="flexiselDemo3">
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/6.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/5.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/1.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/4.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/6.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
				<li>
					<a href="#">
						<div class="banner-1">
							<img src="{% static 'images/1.jpg' %}" class="img-responsive" alt="">
						</div>
					</a>
				</li>
			</ul>

							 <script type="text/javascript">
								$(window).load(function() {

									$("#flexiselDemo3").flexisel({
										visibleItems: 5,
										animationSpeed: 1000,
										autoPlay: true,
										autoPlaySpeed: 3000,
										pauseOnHover: true,
										enableResponsiveBreakpoints: true,
										responsiveBreakpoints: {
											portrait: {
												changePoint:480,
												visibleItems: 2
											},
											landscape: {
												changePoint:640,
												visibleItems: 3
											},
											tablet: {
												changePoint:768,
												visibleItems: 3
											}
										}
									});

								});
								</script>
								<script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
					<div class="clearfix"> </div>
		</div>

templates/base.html
{% load static %}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>Voguish  | {% block title %}{% endblock %}</title>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Voguish Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,700' rel='stylesheet' type='text/css'>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/responsiveslides.min.js' %}"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });

  </script>

</head>
<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="{% url 'home:home' %}"><img src="{% static 'images/logo.png' %}" class="img-responsive" alt=""></a>
			</div>

            {% block navigation %}

            {% endblock %}


						<!-- script-for-nav -->
							<script>
								$( "span.menu" ).click(function() {
								  $( ".head-nav ul" ).slideToggle(300, function() {
									// Animation complete.
								  });
								});
							</script>
						<!-- script-for-nav -->



					<div class="clearfix"> </div>
		</div>
	</div>
<!-- header -->
<div class="container">

    {% block content %}


    {% endblock %}

    {% block recent %}


    {% endblock %}


	<div class="clearfix"> </div>
    {% block banner %}

    {% endblock %}


		<div class="footer">
			<div class="col-md-3 foot-1">
				<h4>Quick Links</h4>
				<ul>
					<li><a href="#">||   Lorem Ipsum passage</a></li>
					<li><a href="#">||   Finibus Bonorum et</a></li>
					<li><a href="#">||   Treatise on the theory</a></li>
				</ul>
			</div>
			<div class="col-md-3 foot-1">
				<h4>Favorite Resources</h4>
				<ul>
					<li><a href="#">||   Characteristic words</a></li>
					<li><a href="#">||   combined with a handful</a></li>
					<li><a href="#">||   which looks reasonable</a></li>
				</ul>
			</div>
			<div class="col-md-3 foot-1">
				<h4>About Us</h4>
				<ul>
					<li><a href="#">||  Even slightly believable</a></li>
					<li><a href="#">||  Hidden in the middle</a></li>
					<li><a href="#">||  Ipsum therefore always</a></li>
				</ul>
			</div>
			<div class="col-md-3 foot-1">
				<h4>Custom Menu</h4>
				<ul>
					<li><a href="#">||  Internet tend to repeat</a></li>
					<li><a href="#">||  Alteration in some form</a></li>
					<li><a href="#">||  This book is a treatise</a></li>
				</ul>
			</div>

			<div class="clearfix"> </div>
			<div class="copyright">
				<p>Copyrights © 2017 Voguish Inc. All rights reserved | Template by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
		</div>
	</div>
</body>
</html>

templates/nav.html
<div class="head-nav">
    <span class="menu"> </span>
        <ul class="cl-effect-1">
            <li {% if is_home %}class="active"{% endif %} ><a href="{% url 'home:home' %}">Home</a></li>
            <li {% if is_about %}class="active"{% endif %} ><a href="{% url 'about' %}">About Us</a></li>
            <li {% if is_services %}class="active"{% endif %} ><a href="{% url 'services' %}">Services</a></li>
            <li {% if is_blog %}class="active"{% endif %} ><a href="{% url 'blog:post_list' %}">Blog</a></li>
{#            <li {% if is_loghin %}class="active"{% endif %} ><a href="login.html">Login</a></li>#}
            <li {% if is_contact %}class="active"{% endif %} ><a href="{% url 'contact:contact' %}">Contact</a></li>
                        <div class="clearfix"></div>
        </ul>
</div>

templates/pagination.html
<!--start-blog-pagenate-->
<nav>
  <ul class="pagination">
    <li>
        {% if page.has_previous %}
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">«</span>
      </a>
        {% endif %}
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
         {% if page.has_next %}
              <a href="#" aria-label="Next">
                <span aria-hidden="true">»</span>
              </a>
        {% endif %}
    </li>
  </ul>
</nav>
<!--//End-blog-pagenate-->

{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page.has_previous %}#}
{#            <a href="?page={{ page.previous_page_number }}">Previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page.number }} of {{ page.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page.has_next %}#}
{#            <a href="?page={{ page.next_page_number }}">Next</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}

templates/recent.html
{% load static %}
<div class="col-md-3 bann-left">
    {% include "search.html" %}

		<h3>Recent Posts</h3>
		<div class="blo-top">

            {% for post in latest_posts %}

			<div class="blog-grids">
				<div class="blog-grid-left">
					<a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" class="img-responsive" alt=""></a>
				</div>
				<div class="blog-grid-right">
					<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
					<p>{{ post.body|truncatechars:45 }}...</p>
				</div>
				<div class="clearfix"> </div>
			</div>

             {% endfor %}

		</div>
		<h3>Categories</h3>
		<div class="blo-top">
			<li><a href="#">||   Lorem Ipsum passage</a></li>
			<li><a href="#">||   Finibus Bonorum et</a></li>
			<li><a href="#">||   Treatise on the theory</a></li>
			<li><a href="#">||   Characteristic words</a></li>
			<li><a href="#">||   combined with a handful</a></li>
			<li><a href="#">||   which looks reasonable</a></li>
		</div>
		<h3>Newsletter</h3>


        <div class="blo-top">
            <form method="post" action=" " >{% csrf_token %}
			<div class="name">
					<input type="email" placeholder="email" name="email" required="">
            </div>
			<div class="button">

					<input type="submit" value="Subscribe">

			</div>
				<div class="clearfix"> </div>
            </form>
		</div>
	</div>

templates/search.html
<div class="b-search">
    <form method='GET' action="{% url 'blog:post_list' %}">
        <input type="text" name='q' value="{{ request.GET.q }}" placeholder='Search posts' onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
        <input type="submit" value="">
    </form>
</div>

templates/services.html
{% extends "base.html" %}
{% load static %}

{% block title %}Services{% endblock %}

{% block navigation %}
    {% include "nav.html" with is_services=True %}
{% endblock %}

{% block content %}

    <div class="service-top">
 			<h3 class="m_3">Services</h3>
	 		<div class="service_grid1">
					<div class="col-md-6 ser-vd">
						<iframe width="100%" height="350" src="https://www.youtube.com/embed/3gKF5XrFStI" frameborder="0" allowfullscreen=""></iframe>
					</div>
					<div class="col-md-6 service_grid1-right">
						<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
		                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly in some form, by injected humour, or randomised words which don't look even slightly believable</p>
					</div>
						<div class="clearfix"> </div>
			  </div>
			  <div class="grid_1 text-center">
    				<h3 class="m_3">Our Core Services</h3>

			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon1"> </i>
			    	  	<h3>Web Design</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon2"> </i>
			    	  	<h3>Web Development</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon3"> </i>
			    	  	<h3>Simple and Clean</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="clearfix"> </div>


			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon4"> </i>
			    	  	<h3>High Quality</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon5"> </i>
			    	  	<h3>Responsive Design</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="col-md-4 box_1">
			    	  	<i class="icon6"> </i>
			    	  	<h3>Easy to Customize</h3>
			    	  	<p>Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus Morbi in dui quis est pulvinar</p>
			    	  </div>
			    	  <div class="clearfix"> </div>

     		 </div>
	    </div>
{% endblock %}

templates/tags.html
<div class="b-tag-weight">
    <h3>Tags Weight</h3>
    {% for post in posts %}

    <ul>
        {% for tag in post.tags.all  %}
        <li><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
        {% endfor %}
</div>

templates/twitter.html
<div class="twitter-weights">
    <h3>Tweet Widget</h3>
    <div class="twitter-weight-grid">
        <h4><span> </span>John Doe</h4>
        <p>Lorem ipsum dolor sit amet, consectetur elit,labore et dolore magna aliqua. <a href="#">http://t.co/h12k</a></p>
        <i><a href="#">2 days ago</a></i>
    </div>
    <div class="twitter-weight-grid">
        <h4><span> </span>John Doe</h4>
        <p>Lorem ipsum dolor sit amet, consectetur elit,labore et dolore magna aliqua. <a href="#">http://t.co/h12k</a></p>
        <i><a href="#">2 days ago</a></i>
    </div>
    <a class="twittbtn" href="#">See all Tweets</a>
</div>